version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 8876:80

        depends_on:
            - app
        container_name: sms_nginx

    app:
        build:
            context: ../SMS
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: sms_app

